name: sitegen
description: Static site generator for Dart, webserver included.
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-sitegen

version: 1.2.0

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/sitegen.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  sitegen:

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  validate: ^1.0.0

  args: ^0.13.0
  path: ^1.3.0
  yaml: ^2.1.0
  markdown: ^0.8.0
  mustache: ^0.2.0
  intl: ^0.12.0
  http_server: ^0.9.0

  system_info: 0.0.16

dev_dependencies:
  test: any